### PR TITLE
Add missing resources to e2e-test-clean

### PR DESCRIPTION
**Pull request by susana-garcia**
## Summary

Add missing resources to e2e-test-clean

## Checklist

- [X] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [X] I have run `make test-e2e` and e2e tests pass successfully

### CODE REVIEW

**Comment by wejdross** [comment]
shouldn't that be cleaned automagically by kuttl?

**Review by glrf — APPROVED** [review]

**Comment by glrf** [comment]
> shouldn't that be cleaned automagically by kuttl?

I guess this is more of a fallback if kuttl fails? :shrug:

**Comment by zugao** [comment]
> I guess this is more of a fallback if kuttl fails? 🤷

This makes sure we don't leave services running indefinitely on Exoscale when we remove a local cluster.

**Review by zugao — APPROVED** [review]
LGTM

**Pull request merged**
